baseurl = "http://jugpy.org/"
languageCode = "es-PY"
title = "Grupo de Usuarios Java del Paraguay"

[author]
name = "JUGPy"
# email will use for gravatar
email = "contacto.jugpy@gmail.com"

[taxonomies]
category = "categories"

[params]
# site description, will show under navigation
description = "Sitio web oficial del Grupo de Usuarios Java del Paraguay (Paraguay Java User Group - JUGPy)"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss = "/index.xml"
subscribe_email = ""

# social links
facebook_user = ""
googleplus_user = "105656225571806435197"
twitter_user = "jugpy"
github_user = "jugpy"

# share links
facebook_like = true
twitter_tweet_button = true
google_plus_one = true

# Disqus Comments
disqus_short_name = "jugpy"
disqus_show_comment_count = true

# google analytics
#google_analytics_tracking_id = ""
